//
//  Food.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Food: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _name: String?
    var _calories: NSNumber?
    var _fat: NSNumber?
    var _protein: NSNumber?
    var _servingSize: NSNumber?
    var _sodium: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "hpet-mobilehub-642847546-Food"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_name"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_name" : "name",
               "_calories" : "calories",
               "_fat" : "fat",
               "_protein" : "protein",
               "_servingSize" : "servingSize",
               "_sodium" : "sodium",
        ]
    }
}
