//
//  Pet.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Pet: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _petId: String?
    var _petAge: NSNumber?
    var _petBreed: String?
    var _petName: String?
    var _petWeight: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "hpet-mobilehub-642847546-Pet"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_petId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_petId" : "petId",
               "_petAge" : "petAge",
               "_petBreed" : "petBreed",
               "_petName" : "petName",
               "_petWeight" : "petWeight",
        ]
    }
}
